todoapplication/todoproject/todoapp/urls.py
from django.urls import path
from .import views
app_name='todoapp'
urlpatterns=[
    path('',views.add,name='add'),
    # path('details',views.details,name='details'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='cbvdelete'),
]

todoapplication/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

todoapplication/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=200)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoapplication/todoproject/todoapp/forms.py
from django import forms
from .models import Task
class ToDoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoapplication/todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

# Create your views here.
from .models import Task
from .forms import ToDoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class TaskListview(ListView):
    model=Task
    template_name='home.html'
    context_object_name='key1'
class TaskDetailview(DetailView):
    model=Task
    template_name='details.html'
    context_object_name='task'
class TaskUpdateview(UpdateView):
    model=Task
    template_name='update.html'
    context_object_name='task'

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs=[{'pk':self.object.id}])
class TaskDeleteview(DeleteView):
    model=Task
    template_name='delete.html'
    # def get_success_url(self):
    #     return reverse('todoapp:cbvhome')
    success_url = reverse_lazy('todoapp:cbvhome')


def add(request):
    task1=Task.objects.all()
    if request.method=="POST":
        name=request.POST.get('task','')
        priority1=request.POST.get('priority','')
        date1=request.POST.get('date','')
        task=Task(name=name,priority=priority1,date=date1)
        task.save()

    return render(request,"home.html",{'key1':task1})
# def details(request):
#     task=Task.objects.all()
#     return render(request,"details.html",{'task':task})
#
def delete(request,taskid):
    task2=Task.objects.get(id=taskid)
    if request.method=="POST":
        task2.delete()
        return redirect('/')
    return render(request,"delete.html")
def update(request,id):
    task=Task.objects.get(id=id)
    form1=ToDoForm(request.POST or None,instance=task)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form1,'task':task})

todoapplication/todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoapplication/todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    Do you want to delete ths task?
    <button type="submit" >Confirm</button>
</form>
{% endblock %}

todoapplication/todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}

<div class="shadow card">
                <div class="card-body">
                    <h4 >{{task.name}}</h4>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">Update</a>
                </div>
            </div>
{% endblock %}

todoapplication/todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoapplication/todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1 class="banner-title">To Do Application</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
    {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="task" placeholder="Enter the Task Name">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="Set Priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" placeholder="Set Date">
                </div>
                <div class="form-group">
                     <input type="submit" class="btn btn-success">
                </div>

</form>
        </div>
        <div class="col-md-6">
            <h1>Task to be Completed</h1>

          {% for i in key1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h4 >{{i.name}}</h4>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
       {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

todoapplication/todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="post">
            {% csrf_token %}
            {{form.as_p}}
           <button type="submit">Confirm</button>
</form>
        </div>
    </div>
</div>

{% endblock %}